name: Laravel CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: PHPのセットアップ
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql, intl, bcmath
          tools: composer:v2

      - name: Composer のキャッシュを利用
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Composer で依存関係をインストール
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: .env の作成
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: データベースのマイグレーション
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --force
    
          # Node.js のセットアップ
      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # npm パッケージのインストール
      - name: npm パッケージのインストール
        run: npm install

      # Vite のビルド
      - name: Vite ビルド
        run: npm run build

      - name: PHPUnit テストの実行
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test
